# Generated by Django 6.1.1 on 2026-09-22 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='award', max_length=50)),
                ('category', models.CharField(default='General', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='hints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='space_complexity',
            field=models.CharField(blank=True, default='O(1)', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_complexity',
            field=models.CharField(blank=True, default='O(N)', max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('Arrays', 'Arrays'), ('Strings', 'Strings'), ('Hash Maps', 'Hash Maps'), ('Linked Lists', 'Linked Lists'), ('Stacks', 'Stacks'), ('Queues', 'Queues'), ('Trees', 'Trees'), ('Graphs', 'Graphs'), ('Recursion', 'Recursion'), ('Sorting', 'Sorting'), ('Searching', 'Searching'), ('Dynamic Programming', 'Dynamic Programming'), ('Greedy Algorithms', 'Greedy Algorithms')], default='Arrays', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Runtime Error', 'Runtime Error'), ('Compilation Error', 'Compilation Error'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Memory Limit Exceeded', 'Memory Limit Exceeded')], default='Wrong Answer', max_length=30),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('streak', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('daily_challenge_completed', models.BooleanField(default=False)),
                ('unlocked_badges', models.ManyToManyField(blank=True, related_name='users', to='api.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
